#include "LUTLoader.hpp"

#include <toml++/toml.hpp>
#include <filesystem>
#include <fstream>

namespace quantiloom {

// ============================================================================
// Helper: Read array of f32 from TOML array node
// ============================================================================

static bool ReadF32Array(const toml::array* arr, std::vector<f32>& out) {
    if (!arr) return false;

    out.clear();
    out.reserve(arr->size());

    for (const auto& elem : *arr) {
        if (auto val = elem.value<double>()) {
            out.push_back(static_cast<f32>(*val));
        } else {
            return false;
        }
    }

    return !out.empty();
}

// ============================================================================
// Public API: LoadTOML
// ============================================================================

std::optional<AtmosphereLUT> LUTLoader::LoadTOML(const std::string& filepath) {
    if (!FileExists(filepath)) {
        QL_LOG_ERROR("LUTLoader::LoadTOML: File not found: {}", filepath);
        return std::nullopt;
    }

    try {
        toml::table tbl = toml::parse_file(filepath);
        AtmosphereLUT lut;

        // Read [data] section
        auto* data = tbl["data"].as_table();
        if (!data) {
            QL_LOG_ERROR("LUTLoader::LoadTOML: Missing [data] section in {}", filepath);
            return std::nullopt;
        }

        // Read arrays
        if (!ReadF32Array((*data)["wavelengths"].as_array(), lut.wavelengths)) {
            QL_LOG_ERROR("LUTLoader::LoadTOML: Missing or invalid 'wavelengths' array");
            return std::nullopt;
        }

        if (!ReadF32Array((*data)["solar_irradiance"].as_array(), lut.solar_irradiance)) {
            QL_LOG_ERROR("LUTLoader::LoadTOML: Missing or invalid 'solar_irradiance' array");
            return std::nullopt;
        }

        if (!ReadF32Array((*data)["sky_radiance"].as_array(), lut.sky_radiance)) {
            QL_LOG_ERROR("LUTLoader::LoadTOML: Missing or invalid 'sky_radiance' array");
            return std::nullopt;
        }

        if (!ReadF32Array((*data)["transmittance"].as_array(), lut.transmittance)) {
            QL_LOG_ERROR("LUTLoader::LoadTOML: Missing or invalid 'transmittance' array");
            return std::nullopt;
        }

        // Read [metadata] section (optional)
        if (auto* meta = tbl["metadata"].as_table()) {
            for (const auto& [key, val] : *meta) {
                if (auto str = val.value<std::string>()) {
                    lut.metadata[std::string(key.str())] = *str;
                }
            }
        }

        // Validate
        if (!lut.IsValid()) {
            QL_LOG_ERROR("LUTLoader::LoadTOML: Loaded LUT failed validation");
            return std::nullopt;
        }

        QL_LOG_INFO("LUTLoader::LoadTOML: Loaded LUT with {} wavelength samples from {}",
                    lut.Size(), filepath);
        return lut;

    } catch (const toml::parse_error& err) {
        QL_LOG_ERROR("LUTLoader::LoadTOML: Parse error in {}: {}", filepath, err.description());
        return std::nullopt;
    }
}

// ============================================================================
// Public API: SaveTOML
// ============================================================================

bool LUTLoader::SaveTOML(const std::string& filepath, const AtmosphereLUT& lut) {
    if (!lut.IsValid()) {
        QL_LOG_ERROR("LUTLoader::SaveTOML: Invalid LUT");
        return false;
    }

    try {
        toml::table tbl;

        // Build [metadata] section
        toml::table meta;
        for (const auto& [key, value] : lut.metadata) {
            meta.insert(key, value);
        }
        tbl.insert("metadata", std::move(meta));

        // Build [data] section
        toml::table data;

        // Convert vectors to TOML arrays
        toml::array wavelengths_arr;
        for (f32 v : lut.wavelengths) wavelengths_arr.push_back(static_cast<double>(v));

        toml::array solar_arr;
        for (f32 v : lut.solar_irradiance) solar_arr.push_back(static_cast<double>(v));

        toml::array sky_arr;
        for (f32 v : lut.sky_radiance) sky_arr.push_back(static_cast<double>(v));

        toml::array trans_arr;
        for (f32 v : lut.transmittance) trans_arr.push_back(static_cast<double>(v));

        data.insert("wavelengths", std::move(wavelengths_arr));
        data.insert("solar_irradiance", std::move(solar_arr));
        data.insert("sky_radiance", std::move(sky_arr));
        data.insert("transmittance", std::move(trans_arr));

        tbl.insert("data", std::move(data));

        // Write to file
        std::ofstream file(filepath);
        if (!file.is_open()) {
            QL_LOG_ERROR("LUTLoader::SaveTOML: Cannot open file for writing: {}", filepath);
            return false;
        }

        file << "# Quantiloom Atmosphere LUT\n";
        file << "# Generated by LUTLoader\n\n";
        file << tbl;

        QL_LOG_INFO("LUTLoader::SaveTOML: Saved LUT with {} wavelength samples to {}",
                    lut.Size(), filepath);
        return true;

    } catch (const std::exception& e) {
        QL_LOG_ERROR("LUTLoader::SaveTOML: Error writing {}: {}", filepath, e.what());
        return false;
    }
}

// ============================================================================
// Public API: FileExists
// ============================================================================

bool LUTLoader::FileExists(const std::string& filepath) {
    return std::filesystem::exists(filepath) &&
           std::filesystem::is_regular_file(filepath);
}

// ============================================================================
// Public API: GetWavelengthRange
// ============================================================================

std::optional<std::pair<f32, f32>> LUTLoader::GetWavelengthRange(const std::string& filepath) {
    if (!FileExists(filepath)) {
        return std::nullopt;
    }

    try {
        toml::table tbl = toml::parse_file(filepath);

        auto* data = tbl["data"].as_table();
        if (!data) return std::nullopt;

        auto* arr = (*data)["wavelengths"].as_array();
        if (!arr || arr->size() < 2) return std::nullopt;

        auto first = arr->front().value<double>();
        auto last = arr->back().value<double>();

        if (first && last) {
            return std::make_pair(static_cast<f32>(*first), static_cast<f32>(*last));
        }

        return std::nullopt;

    } catch (const toml::parse_error& err) {
        QL_LOG_ERROR("LUTLoader::GetWavelengthRange: Parse error: {}", err.description());
        return std::nullopt;
    }
}

} // namespace quantiloom
