#pragma once

#include "core/Types.hpp"
#include "core/SpectralData.hpp"
#include "core/Log.hpp"
#include <string>
#include <vector>
#include <unordered_map>
#include <filesystem>

// ============================================================================
// SpectralBasisLoader - Load SpectralBaker NMF basis functions and materials
// ============================================================================
// Loads pre-computed NMF basis functions and material weights generated by
// SpectralBaker. Reconstructs full spectral curves at runtime by computing
// spectrum = sum(weight[i] * basis[i]) for each band.
//
// File formats:
// - quantiloom_basis_v1.bin: Binary file with per-band basis functions
// - quantiloom_materials.json: JSON database with material weights
//
// Binary format v2 (little-endian):
//   Header (64 bytes):
//     - magic: 4 bytes ("QBAS")
//     - version: uint32 (2)
//     - num_bands: uint32
//     - reserved: 52 bytes
//
//   Per-band:
//     BandHeader (16 bytes):
//       - wavelength_start: float32 (micrometers)
//       - wavelength_end: float32 (micrometers)
//       - num_samples: uint32
//       - num_basis: uint32 (per-band basis count)
//     BandData:
//       - basis_data: float32[num_basis * num_samples] (row-major)
//
// JSON format:
//   {
//     "metadata": { ... },
//     "materials": {
//       "Material_Name": {
//         "source": { filename, record_id, instrument, chapter },
//         "bands": {
//           "VIS": { basis_weights: [...], rmse, explained_variance },
//           "NIR": { ... },
//           "SWIR": { ... }
//         }
//       }
//     }
//   }
// ============================================================================

namespace quantiloom {

// NMF Band names used by SpectralBaker (renamed to avoid conflict with Scene.hpp)
enum class NMFBandType : u32 {
    VIS = 0,   // Visible (350-780nm)
    NIR = 1,   // Near-IR (780-1100nm)
    SWIR = 2,  // Short-wave IR (1100-2500nm)
    Count = 3
};

// Convert band enum to string
inline const char* NMFBandTypeToString(NMFBandType band) {
    switch (band) {
        case NMFBandType::VIS:  return "VIS";
        case NMFBandType::NIR:  return "NIR";
        case NMFBandType::SWIR: return "SWIR";
        default: return "Unknown";
    }
}

// ============================================================================
// BasisFunctions - Stores NMF basis functions for a single band
// ============================================================================
struct BasisFunctions {
    String name;                          // Band name (VIS, NIR, SWIR)
    f32 wavelengthStart_um = 0.0f;        // Start wavelength (micrometers)
    f32 wavelengthEnd_um = 0.0f;          // End wavelength (micrometers)
    u32 numSamples = 0;                   // Wavelength samples count
    u32 numBasis = 0;                     // Number of basis functions
    std::vector<f32> data;                // [numBasis * numSamples] row-major

    // Get wavelength at sample index (uniform sampling)
    [[nodiscard]] f32 GetWavelength_nm(u32 sampleIndex) const {
        if (numSamples <= 1) return wavelengthStart_um * 1000.0f;
        f32 t = static_cast<f32>(sampleIndex) / static_cast<f32>(numSamples - 1);
        return (wavelengthStart_um + t * (wavelengthEnd_um - wavelengthStart_um)) * 1000.0f;
    }

    // Get basis function value at (basisIndex, sampleIndex)
    [[nodiscard]] f32 Get(u32 basisIndex, u32 sampleIndex) const {
        return data[basisIndex * numSamples + sampleIndex];
    }

    // Check if valid
    [[nodiscard]] bool IsValid() const {
        return numBasis > 0 && numSamples > 0 && data.size() == numBasis * numSamples;
    }
};

// ============================================================================
// MaterialSpectralData - Stores NMF weights for a single material
// ============================================================================
struct MaterialSpectralData {
    String name;                          // Material name (key in JSON)
    String filename;                      // Source filename
    String recordId;                      // USGS record ID
    String instrument;                    // Spectrometer (ASDFRa, etc.)
    String chapter;                       // USGS chapter

    // Per-band data
    struct BandData {
        std::vector<f32> weights;         // NMF weights [numBasis]
        f32 rmse = 0.0f;                  // Reconstruction RMSE
        f32 explainedVariance = 0.0f;     // Explained variance ratio
    };

    std::unordered_map<String, BandData> bands;  // "VIS", "NIR", "SWIR"

    // Check if material has data for a specific band
    [[nodiscard]] bool HasBand(const String& bandName) const {
        return bands.find(bandName) != bands.end();
    }
};

// ============================================================================
// SpectralBasisLoader - Main loader class
// ============================================================================
class QL_API SpectralBasisLoader {
public:
    SpectralBasisLoader() = default;

    // ========================================================================
    // Loading
    // ========================================================================

    // Load basis functions from binary file
    // @param basisFilePath: Path to quantiloom_basis_v1.bin
    // @return: True on success
    bool LoadBasis(const std::filesystem::path& basisFilePath);

    // Load material weights from JSON file
    // @param jsonFilePath: Path to quantiloom_materials.json
    // @return: True on success
    bool LoadMaterials(const std::filesystem::path& jsonFilePath);

    // Load both files at once (convenience)
    bool Load(const std::filesystem::path& basisFilePath,
              const std::filesystem::path& jsonFilePath) {
        return LoadBasis(basisFilePath) && LoadMaterials(jsonFilePath);
    }

    // ========================================================================
    // Queries
    // ========================================================================

    // Check if basis data is loaded
    [[nodiscard]] bool HasBasis() const { return !m_basisFunctions.empty(); }

    // Check if materials data is loaded
    [[nodiscard]] bool HasMaterials() const { return !m_materials.empty(); }

    // Get number of loaded materials
    [[nodiscard]] size_t GetMaterialCount() const { return m_materials.size(); }

    // Get all material names
    [[nodiscard]] std::vector<String> GetMaterialNames() const;

    // Find material by name (exact match)
    // @return: Pointer to material data, or nullptr if not found
    [[nodiscard]] const MaterialSpectralData* FindMaterial(const String& name) const;

    // Find material by partial name (case-insensitive substring match)
    // @return: Pointer to first matching material, or nullptr if not found
    [[nodiscard]] const MaterialSpectralData* FindMaterialPartial(const String& pattern) const;

    // Get basis functions for a specific band
    // @return: Pointer to basis functions, or nullptr if band not found
    [[nodiscard]] const BasisFunctions* GetBasis(const String& bandName) const;
    [[nodiscard]] const BasisFunctions* GetBasis(NMFBandType band) const {
        return GetBasis(NMFBandTypeToString(band));
    }

    // ========================================================================
    // Spectral Reconstruction
    // ========================================================================

    // Reconstruct spectral curve for a material and band
    // Computes: spectrum[i] = sum(weights[j] * basis[j][i])
    //
    // @param materialName: Name of the material in JSON database
    // @param bandName: Band name ("VIS", "NIR", "SWIR")
    // @return: Reconstructed SpectralCurve, empty on error
    [[nodiscard]] SpectralCurve ReconstructCurve(const String& materialName,
                                                  const String& bandName) const;

    // Reconstruct and convert to GPU format (64 uniform samples)
    // @param materialName: Name of the material
    // @param bandName: Band name
    // @return: SpectralCurveGPU ready for GPU upload
    [[nodiscard]] SpectralCurveGPU ReconstructCurveGPU(const String& materialName,
                                                        const String& bandName) const;

    // Reconstruct full spectrum across all bands
    // Combines VIS+NIR+SWIR into a single curve (350-2500nm)
    // @param materialName: Name of the material
    // @return: Combined SpectralCurve spanning all bands
    [[nodiscard]] SpectralCurve ReconstructFullSpectrum(const String& materialName) const;

    // ========================================================================
    // Metadata
    // ========================================================================

    // Binary file metadata
    [[nodiscard]] u32 GetBasisVersion() const { return m_basisVersion; }
    [[nodiscard]] u32 GetNumBands() const { return static_cast<u32>(m_basisFunctions.size()); }

    // JSON metadata
    [[nodiscard]] const String& GetGenerator() const { return m_generator; }
    [[nodiscard]] const String& GetSourceLibrary() const { return m_sourceLibrary; }
    [[nodiscard]] const String& GetDateGenerated() const { return m_dateGenerated; }

private:
    // Binary file data
    u32 m_basisVersion = 0;
    std::unordered_map<String, BasisFunctions> m_basisFunctions;  // Band name -> basis

    // JSON file data
    String m_generator;
    String m_sourceLibrary;
    String m_dateGenerated;
    std::unordered_map<String, MaterialSpectralData> m_materials;  // Material name -> data

    // Internal helpers
    bool ParseBasisHeader(const std::vector<u8>& data, size_t& offset);
    bool ParseBandData(const std::vector<u8>& data, size_t& offset);
};

} // namespace quantiloom
