#!/usr/bin/env python3
"""Pair CIE D65 with a Rayleigh-scattered sky, as a two-spectrum solar LUT.

`CIE_std_illum_D65.csv` carries ONE spectrum, so a scene using it has to say
`solar_lut_columns = [2, 0]` -- no diffuse column -- and gets a black sky. This
writes the same D65 beam alongside a sky spectrum so a scene can have both.

THE SKY MODEL, stated plainly because it is an approximation and the renderer is
meant for quantitative work:

    sky(lambda) = D65(lambda) * (lambda / 560)^-4,  scaled to SKY_LUMINANCE_FRAC

That is single-scattering Rayleigh and nothing else. The lambda^-4 comes from
the Rayleigh cross-section, which is why a clear sky is blue. What it leaves out:

  - ozone's Chappuis absorption near 600 nm, which deepens real sky blue
  - aerosol (Mie) scattering, which is far less wavelength-dependent and washes
    the blue out towards the horizon
  - multiple scattering, ground albedo coupling, and any angular dependence at
    all -- this is one spectrum for the whole dome

For a sky that models those, use the NN atmosphere ([atmosphere] in the scene
config); it is a MODTRAN surrogate and covers every band. This file exists for
scenes that only need "a plausible blue sky with a D65 sun and a neutral white
point", which is what an sRGB-referenced test render wants.

The ratio is set by luminance, not by peak: SKY_LUMINANCE_FRAC of the beam's,
which is in the range clear-sky diffuse-to-direct usually falls in.

    python3 scripts/make_d65_sun_sky.py
"""
import argparse
import pathlib

import numpy as np

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / "assets/luts/CIE_std_illum_D65.csv"
CMF = ROOT / "assets/luts/CIE_xyz_1931_2deg.csv"


RAYLEIGH_REF_NM = 560.0      # normalisation pivot; only the shape matters

ap = argparse.ArgumentParser()
ap.add_argument("--exponent", type=float, default=4.0,
                help="lambda^-N. 4 is pure Rayleigh (molecular). A real clear "
                     "sky is LESS saturated than that because aerosol (Mie) "
                     "scattering is nearly wavelength-neutral and dilutes it; "
                     "2 to 3 is closer to what a camera records.")
ap.add_argument("--sky-fraction", type=float, default=0.15,
                help="diffuse luminance as a fraction of the beam's")
ap.add_argument("--out", default="assets/luts/D65_sun_rayleigh_sky.csv")
args = ap.parse_args()
SKY_LUMINANCE_FRAC = args.sky_fraction


def load_two_columns(path):
    rows = []
    for line in path.read_text(encoding="utf-8-sig").splitlines():
        line = line.strip()
        if not line or line[0] in "#;":
            continue
        parts = line.replace(",", " ").split()
        try:
            rows.append((float(parts[0]), float(parts[1])))
        except (ValueError, IndexError):
            continue          # header or malformed line
    return np.array(rows)


d65 = load_two_columns(SRC)
nm, power = d65[:, 0], d65[:, 1]

cmf = np.loadtxt(CMF, delimiter=",")
ybar = np.interp(nm, cmf[:, 0], cmf[:, 2])     # column 2 is y-bar


def luminance(spectrum):
    return float(np.trapezoid(spectrum * ybar, nm))


OUT = ROOT / args.out
sky = power * (nm / RAYLEIGH_REF_NM) ** -args.exponent
sky *= SKY_LUMINANCE_FRAC * luminance(power) / luminance(sky)

lines = [
    "# CIE standard illuminant D65 paired with a Rayleigh-scattered sky.",
    "# Generated by scripts/make_d65_sun_sky.py -- do not edit by hand.",
    "#",
    "# Column 2 is D65 exactly as published (see assets/luts/README.md for its",
    f"# DOI). Column 3 is D65 * (lambda/560)^-{args.exponent:g}, a single-scattering sky and",
    "# nothing more: no ozone Chappuis band, no multiple scattering, no angular",
    "# variation. Use the NN atmosphere if those matter.",
    "#",
    "# Exponent 4 is pure Rayleigh and renders BLUER than a photograph, because a",
    "# real clear sky also carries aerosol scattering, which is nearly",
    f"# wavelength-neutral and dilutes the blue. This file uses {args.exponent:g}.",
    "#",
    f"# The sky carries {SKY_LUMINANCE_FRAC:.0%} of the beam's luminance.",
    "#",
    "# Usage:",
    "#   solar_lut = \"assets/luts/D65_sun_rayleigh_sky.csv\"",
    "#   solar_lut_columns = [2, 3]",
    "#   solar_lut_normalise = \"unit_luminance\"",
    "#",
    "# wavelength_nm  direct(D65)  diffuse(Rayleigh sky)",
]
for w, p, s in zip(nm, power, sky):
    lines.append(f"{w:.1f}\t{p:.6f}\t{s:.6f}")

OUT.write_text("\n".join(lines) + "\n")

# Report the colours so the file can be checked without rendering.
M = np.array([[3.2406, -1.5372, -0.4986],
              [-0.9689, 1.8758, 0.0415],
              [0.0557, -0.2040, 1.0570]])
xbar = np.interp(nm, cmf[:, 0], cmf[:, 1])
zbar = np.interp(nm, cmf[:, 0], cmf[:, 3])


def to_srgb(spectrum):
    xyz = np.array([float(np.trapezoid(spectrum * c, nm)) for c in (xbar, ybar, zbar)])
    return (xyz / luminance(power)) @ M.T


sun_rgb, sky_rgb = to_srgb(power), to_srgb(sky)
try:
    shown = OUT.relative_to(ROOT)
except ValueError:
    shown = OUT
print(f"wrote {shown}  ({len(nm)} rows, {nm[0]:.0f}-{nm[-1]:.0f} nm)")
print(f"  sun linear sRGB (Y=1) : [{sun_rgb[0]:.4f}, {sun_rgb[1]:.4f}, {sun_rgb[2]:.4f}]"
      f"   <- D65 is sRGB white by definition")
print(f"  sky linear sRGB       : [{sky_rgb[0]:.4f}, {sky_rgb[1]:.4f}, {sky_rgb[2]:.4f}]"
      f"   B/R = {sky_rgb[2] / sky_rgb[0]:.2f}")
print(f"  sky luminance / sun   : {luminance(sky) / luminance(power):.3f}")
