#!/usr/bin/env python3
"""Bake assets/luts/CIE_illum_FLs.csv into a compiled-in C++ table.

Why compiled in rather than read at run time: the same reason D65Illuminant.hpp
gives. A built-in illuminant a config can name by a short token has to exist
whenever the renderer does, and resolving `emissive_curve = "cie_f7"` against a
file that may or may not be beside the executable turns a typo in an asset path
into a silently different lamp. The CSV stays in assets/luts/ as provenance --
this script is the link between the two, so the header can be re-derived and
diffed rather than trusted.

Usage (from the repo root):
    python scripts/make_fl_illuminants.py

Writes src/libQuantiloom/core/FluorescentIlluminants.hpp.
"""

from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CSV_PATH = REPO / "assets" / "luts" / "CIE_illum_FLs.csv"
META_PATH = REPO / "assets" / "luts" / "CIE_illum_FLs.csv_metadata.json"
OUT_PATH = REPO / "src" / "libQuantiloom" / "core" / "FluorescentIlluminants.hpp"

EXPECTED_ROWS = 81
EXPECTED_COLS = 28  # wavelength + FL1..FL12 + FL3.1..FL3.15
EXPECTED_MIN_NM = 380.0
EXPECTED_MAX_NM = 780.0
EXPECTED_STEP_NM = 5.0


def main() -> int:
    if not CSV_PATH.exists():
        print(f"missing {CSV_PATH}", file=sys.stderr)
        return 1

    with CSV_PATH.open(newline="", encoding="utf-8") as fh:
        rows = [r for r in csv.reader(fh) if r and r[0].strip()]

    meta = json.loads(META_PATH.read_text(encoding="utf-8"))
    names = [c["title"] for c in meta["datatableInfo"]["columnHeaders"]]
    doi = meta["identifier"]["identifier"]
    year = meta["publicationYear"]
    rights = meta["rightsList"][0]["rights"]

    # Everything downstream indexes this table by arithmetic on the wavelength,
    # so a table that is not the shape we think it is must stop the bake rather
    # than produce a header that compiles and lies.
    if len(rows) != EXPECTED_ROWS:
        print(f"expected {EXPECTED_ROWS} rows, got {len(rows)}", file=sys.stderr)
        return 1
    if len(rows[0]) != EXPECTED_COLS or len(names) != EXPECTED_COLS:
        print(f"expected {EXPECTED_COLS} columns, got {len(rows[0])}/{len(names)}",
              file=sys.stderr)
        return 1

    lam = [float(r[0]) for r in rows]
    if lam[0] != EXPECTED_MIN_NM or lam[-1] != EXPECTED_MAX_NM:
        print(f"expected {EXPECTED_MIN_NM}-{EXPECTED_MAX_NM} nm, got {lam[0]}-{lam[-1]}",
              file=sys.stderr)
        return 1
    for a, b in zip(lam, lam[1:]):
        if abs((b - a) - EXPECTED_STEP_NM) > 1e-9:
            print(f"non-uniform step at {a} nm", file=sys.stderr)
            return 1

    # Column 0 is the wavelength; the other 27 are the lamps, in CIE's order.
    lamps = names[1:]
    values = [[float(r[i]) for i in range(1, EXPECTED_COLS)] for r in rows]

    def token(display: str) -> str:
        # FL7 -> cie_f7, FL3.15 -> cie_f3.15. The token is what a config writes.
        return "cie_f" + display[2:].lower()

    out: list[str] = []
    w = out.append
    w("/**")
    w(" * @file FluorescentIlluminants.hpp")
    w(" * @brief CIE illuminants FL1-FL12 and FL3.1-FL3.15, relative spectral power")
    w(" *")
    w(" * GENERATED by scripts/make_fl_illuminants.py -- do not edit by hand.")
    w(" * Re-run that script to change anything here.")
    w(" *")
    w(f" * Source: International Commission on Illumination (CIE), Vienna, {year}")
    w(f" * DOI: {doi}")
    w(f" * Licence: {rights}")
    w(" * Original: CIE 015:2018 tables 10.1, 10.2 and 10.3, transcribed from")
    w(" * assets/luts/CIE_illum_FLs.csv, which is the CIE's own published dataset.")
    w(" *")
    w(" * Internal, like D65Illuminant.hpp beside it, and compiled in for the same")
    w(" * reason: a built-in a config names by a token must exist whenever the")
    w(" * renderer does.")
    w(" *")
    w(" * These are the only illuminants here with emission LINES rather than a")
    w(" * smooth curve -- mercury's 405, 436, 546 and 578 nm spikes sit on top of")
    w(" * the phosphor continuum. That is the whole reason a fluorescent lamp")
    w(" * cannot be approximated by an RGB triple: the triple integrates the")
    w(" * lines away, and no colour correction puts them back.")
    w(" *")
    w(f" * {EXPECTED_ROWS} samples, {EXPECTED_STEP_NM:.0f} nm, "
      f"{EXPECTED_MIN_NM:.0f}-{EXPECTED_MAX_NM:.0f} nm, normalised to 100 at 560 nm.")
    w(" * Relative, so the absolute level means nothing on its own -- see")
    w(" * ResolveEmissionSpectrum, which is what gives it one.")
    w(" */")
    w("")
    w("#pragma once")
    w("")
    w('#include "core/Types.hpp"')
    w("")
    w("namespace quantiloom {")
    w("")
    w(f"inline constexpr f32 FL_LAMBDA_MIN = {EXPECTED_MIN_NM:.1f}f;")
    w(f"inline constexpr f32 FL_LAMBDA_MAX = {EXPECTED_MAX_NM:.1f}f;")
    w(f"inline constexpr f32 FL_LAMBDA_STEP = {EXPECTED_STEP_NM:.1f}f;")
    w(f"inline constexpr u32 FL_LUT_SIZE = {EXPECTED_ROWS};")
    w(f"inline constexpr u32 FL_LAMP_COUNT = {len(lamps)};")
    w("")
    w("/// The token a config writes, in the same order as the rows of CIE_FL below.")
    w("inline constexpr const char* FL_LAMP_TOKENS[FL_LAMP_COUNT] = {")
    for i in range(0, len(lamps), 6):
        chunk = ", ".join(f'"{token(n)}"' for n in lamps[i:i + 6])
        w(f"    {chunk},")
    w("};")
    w("")
    w("/// [lamp][sample], relative spectral power. Row order matches FL_LAMP_TOKENS.")
    w("inline constexpr f32 CIE_FL[FL_LAMP_COUNT][FL_LUT_SIZE] = {")
    for j, name in enumerate(lamps):
        w(f"    // {name}")
        w("    {")
        col = [values[i][j] for i in range(EXPECTED_ROWS)]
        for i in range(0, EXPECTED_ROWS, 8):
            chunk = ", ".join(f"{v:.2f}f" for v in col[i:i + 8])
            w(f"        {chunk},")
        w("    },")
    w("};")
    w("")
    w("}  // namespace quantiloom")
    w("")

    OUT_PATH.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {OUT_PATH.relative_to(REPO)}: "
          f"{len(lamps)} lamps x {EXPECTED_ROWS} samples")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
