#!/usr/bin/env bash
# PostToolUse hook: warn when build-cdb no longer describes the tree.
#
# clangd reads build-cdb/compile_commands.json (see .clangd). For a source file
# that is not in the database it silently falls back to heuristic flags: wrong
# include paths, missing defines, invented diagnostics -- and no error anywhere
# saying so. The database is only regenerated by hand.
#
# The two things that invalidate it are adding a source file and editing a
# CMakeLists.txt, so check exactly then and stay quiet otherwise.
#
# Uses python3, not jq -- jq is not installed here, and a hook that silently
# no-ops is worse than no hook.
set -uo pipefail
cd "$(dirname "$0")/../.."

CDB=build-cdb/compile_commands.json

f=$(python3 -c 'import json,sys
try: d=json.load(sys.stdin)
except Exception: d={}
print(d.get("tool_input",{}).get("file_path") or d.get("tool_response",{}).get("filePath") or "")' 2>/dev/null)
[ -n "$f" ] || exit 0

case "$f" in
  *.cpp|*.cc|*.cxx|*.c|*/CMakeLists.txt|*.cmake) ;;
  *) exit 0 ;;
esac

# No database at all: clangd is running on heuristics for the whole repo.
if [ ! -f "$CDB" ]; then
  python3 -c 'import json
print(json.dumps({"hookSpecificOutput":{"hookEventName":"PostToolUse","additionalContext":
  "build-cdb/compile_commands.json does not exist, so clangd is guessing compile "
  "flags for every file in this repo -- diagnostics and navigation are unreliable. "
  "Run ./scripts/gen_compile_commands.sh (~13 s)."}}))'
  exit 0
fi

python3 - "$f" "$CDB" <<'PY'
import json, os, sys

target, cdb_path = sys.argv[1], sys.argv[2]
repo = os.getcwd().replace("\\", "/")

# The hook receives a WSL or relative path; the database stores native Windows
# paths (D:/Quantiloom-dev/...). Compare on the repo-relative tail instead.
def rel(p):
    p = os.path.abspath(p).replace("\\", "/")
    return p[len(repo) + 1:] if p.startswith(repo + "/") else os.path.basename(p)

target_rel = rel(target)
msg = None

if target_rel.endswith("CMakeLists.txt") or target_rel.endswith(".cmake"):
    if os.path.getmtime(cdb_path) < os.path.getmtime(target):
        msg = (f"{target_rel} was modified after build-cdb/compile_commands.json was "
               f"generated. If this change added, removed or renamed a source file, or "
               f"changed include directories or compile definitions, clangd is now "
               f"working from stale flags without reporting it. "
               f"Re-run ./scripts/gen_compile_commands.sh (~13 s).")
else:
    try:
        entries = json.load(open(cdb_path, encoding="utf-8"))
    except Exception:
        sys.exit(0)
    known = {e.get("file", "").replace("\\", "/").rsplit(repo.rsplit("/", 1)[-1] + "/", 1)[-1]
             for e in entries}
    if target_rel not in known:
        msg = (f"{target_rel} is not in build-cdb/compile_commands.json, so clangd will "
               f"fall back to heuristic compile flags for it -- diagnostics in this file "
               f"may be wrong in either direction. If you just added it to a CMakeLists, "
               f"re-run ./scripts/gen_compile_commands.sh (~13 s).")

if msg:
    print(json.dumps({"hookSpecificOutput": {"hookEventName": "PostToolUse",
                                             "additionalContext": msg}}))
PY
exit 0
